### ISSUE TITLE
Bazel not finding varref and vardef 

### ISSUE THREAD

**Issue by 0xMihir** [google/nearby#828] opened 2022-08-09 03:13 UTC
Building the library is impossible for me, as Bazel cannot find the names of vardef and varref in the windows client. How do I fix this?

```
ERROR: C:/Users/[user]/nearby/connections/clients/windows/BUILD:51:1: name 'vardef' is not defined
ERROR: C:/Users/[user]/nearby/connections/clients/windows/BUILD:60:15: name 'varref' is not defined
ERROR: C:/Users/[user]/nearby/internal/platform/implementation/BUILD:16:11: no such target '//connections/clients/windows:types': target 'types' not declared in package 'connections/clients/windows' defined by C:/Users/[user]/nearby/connections/clients/windows/BUILD and referenced by '//internal/platform/implementation:types'
INFO: Repository rules_python instantiated at:
  C:/Users/[user]/nearby/WORKSPACE:85:14: in <toplevel>
  C:/Users/[user]/_bazel_[user]/7w2phohm/external/com_google_protobuf/protobuf_deps.bzl:60:21: in protobuf_deps
Repository rule http_archive defined at:
  C:/Users/[user]/_bazel_[user]/7w2phohm/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository rules_proto instantiated at:
  C:/Users/[user]/nearby/WORKSPACE:85:14: in <toplevel>
  C:/Users/[user]/_bazel_[user]/7w2phohm/external/com_google_protobuf/protobuf_deps.bzl:52:21: in protobuf_deps
Repository rule http_archive defined at:
  C:/Users/[user]/_bazel_[user]/7w2phohm/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository com_google_glog instantiated at:
  C:/Users/[user]/nearby/WORKSPACE:55:13: in <toplevel>
Repository rule http_archive defined at:
  C:/Users/[user]/_bazel_[user]/7w2phohm/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: Analysis of target '//connections:core' failed; build aborted:
INFO: Elapsed time: 8.555s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (65 packages loaded, 297 targets configured)
    currently loading: @com_google_protobuf//
```

**Comment by bourdakos1** [comment] 2022-08-09 16:22
Unfortunately, we don't have support for building on Windows yet. This is something we are currently working on, but we have run into a couple of issues that we are still trying to resolve.

**Comment by 0xMihir** [comment] 2022-08-23 19:48
I get this same error trying to build on Mac, but I haven't tried Linux yet. Is mac not supported either?

**Comment by bourdakos1** [comment] 2022-08-23 20:44
I'm not sure if building for Mac through bazel works, but you should be able to use it with swift package manager. The linux build should work, but we don't have any mediums implemented so it won't be very useful.

**Comment by thomaseizinger** [comment] 2023-03-15 20:33
> The linux build should work, but we don't have any mediums implemented so it won't be very useful.  

What do you mean with "no mediums implemeted"? What is a medium in this context?

**Comment by thomaseizinger** [comment] 2023-03-15 20:44
> > The linux build should work, but we don't have any mediums implemented so it won't be very useful.  
> 
> What do you mean with "no mediums implemeted"? What is a medium in this context?
> 

Found it. The README mentions that the WiFi LAN medium is supported. Is that not true?

**Comment by bourdakos1** [comment] 2023-03-15 21:27
The README is a bit unclear, but Wi-Fi LAN is only supported by Apple platforms. Linux has no supported mediums. We should update the documentation to make that apparent.

**Comment by bourdakos1** [comment] 2023-03-19 02:15
Closing as duplicate of #408

**Closed by bourdakos1** 2023-03-19 02:15 UTC
Labels: duplicate
